services:
  database:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - quizquadrant-network
    volumes:
      - quizquadrant-volume:/data/db
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DEVELOPER_EMAIL: ${DEVELOPER_EMAIL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    restart: on-failure:10
    depends_on:
      - database
    networks:
      - quizquadrant-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      NEXT_PUBLIC_BACKEND_BASE_URL: ${NEXT_PUBLIC_BACKEND_BASE_URL}

networks:
  quizquadrant-network:

volumes:
  quizquadrant-volume: